// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	// Fetch available update metadata
	fetchUpdate: () => typedError<{
	version: string,
	currentVersion: string,
	notes: string | null,
	pubDate: string | null,
} | null, UpdaterError>(__TAURI_INVOKE("fetch_update")),
	// Install the pending update
	installUpdate: (onEvent: Channel<DownloadEvent>) => typedError<null, UpdaterError>(__TAURI_INVOKE("install_update", { onEvent })),
	// ## Get process list
	getProcessList: () => __TAURI_INVOKE<ProcessInfo_Serialize[]>("get_process_list"),
	/**
	 *  ## Get CPU usage (%)
	 * 
	 *  - param state: shared `HistoryStore` from the Core collector.
	 *  - return: `i32` overall CPU usage (%)
	 */
	getCpuUsage: () => __TAURI_INVOKE<number>("get_cpu_usage"),
	// ## Get system information
	getHardwareInfo: () => typedError<SysInfo, string>(__TAURI_INVOKE("get_hardware_info")),
	/**
	 *  ## Get detailed memory information
	 * 
	 *  - return: `models::hardware::MemoryInfo` Detailed memory information
	 */
	getMemoryInfoDetail: () => typedError<MemoryInfo, string>(__TAURI_INVOKE("get_memory_info_detail")),
	/**
	 *  ## Get memory usage (%)
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - return: `i32` Memory usage (%)
	 */
	getMemoryUsage: () => __TAURI_INVOKE<number>("get_memory_usage"),
	/**
	 *  ## Get GPU usage (%)
	 * 
	 *  Returns the GPU usage percentage together with the data-source
	 *  identifier (e.g. "NVAPI", "ADL", "PDH", "DRM (AMD)", "IOKit").
	 */
	getGpuUsage: () => typedError<GpuUsageResult, string>(__TAURI_INVOKE("get_gpu_usage")),
	getProcessorsUsage: () => __TAURI_INVOKE<number[]>("get_processors_usage"),
	// ## Get GPU temperature
	getGpuTemperature: () => typedError<NameValue[], string>(__TAURI_INVOKE("get_gpu_temperature")),
	/**
	 *  ## Get CPU usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getCpuUsageHistory: (seconds: number) => __TAURI_INVOKE<number[]>("get_cpu_usage_history", { seconds }),
	/**
	 *  ## Get memory usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getMemoryUsageHistory: (seconds: number) => __TAURI_INVOKE<number[]>("get_memory_usage_history", { seconds }),
	/**
	 *  ## Get GPU usage history
	 * 
	 *  - param state: shared `HistoryStore`.
	 *  - param gpu_id: `String` GPU identifier (e.g. "nvapi:0")
	 *  - param seconds: `u32` Number of seconds to retrieve
	 */
	getGpuUsageHistory: (gpuId: string, seconds: number) => __TAURI_INVOKE<number[]>("get_gpu_usage_history", { gpuId, seconds }),
	// ## Get network information
	getNetworkInfo: () => typedError<NetworkInfo[], BackendError>(__TAURI_INVOKE("get_network_info")),
	/**
	 *  ## Get Super I/O chip-id diagnostics through PawnIO LpcIO
	 * 
	 *  This diagnostic only reads raw chip-id registers (`0x20` / `0x21`) after
	 *  the documented Nuvoton and ITE configuration-mode enter sequences. It does
	 *  not read temperatures, fan counters, voltages, or any hardware-monitor data.
	 */
	getSuperIoChipIdDiagnostics: () => typedError<SuperIoChipIdDiagnostics, string>(__TAURI_INVOKE("get_super_io_chip_id_diagnostics")),
	/**
	 *  ## Get realtime GPU memory usage (best-effort)
	 * 
	 *  **Platform support**: Currently implemented only on macOS. On other
	 *  platforms, or where the underlying APIs are not available, this will
	 *  return `Ok(None)` instead of failing.
	 */
	getGpuMemoryUsage: () => typedError<{
	inUseBytes: string | null,
	allocBytes: string | null,
} | null, string>(__TAURI_INVOKE("get_gpu_memory_usage")),
	// ## Get latest Storage Health records for the dashboard
	getStorageHealthLatestRecords: () => typedError<StorageHealthRecord[], string>(__TAURI_INVOKE("get_storage_health_latest_records")),
	/**
	 *  ## Get Live Storage Health signals (on demand, never persisted — ADR 0006)
	 * 
	 *  Reads the startup-cached device list with one `DeviceIoControl` query
	 *  per device; repeated calls within the core-side minimum interval
	 *  return the last reading. Returns an empty list when
	 *  `storageHealth.enabled` is off or on platforms without the cheap
	 *  native read path (displays fall back to the daily records).
	 */
	getLiveStorageHealth: () => typedError<LiveStorageHealth[], string>(__TAURI_INVOKE("get_live_storage_health")),
	/**
	 *  ## Re-detect Storage Devices
	 * 
	 *  Re-detects connected storage devices, refreshes the Live Storage
	 *  Health cache, collects current Storage Health signals, updates
	 *  today's Storage Health Records, and returns the latest active records
	 *  for the dashboard.
	 */
	refreshStorageDevices: () => typedError<StorageHealthRecord[], string>(__TAURI_INVOKE("refresh_storage_devices")),
	getExternalComponentGuidanceCandidates: (view: ExternalComponentGuidanceView) => typedError<ExternalComponentGuidanceCandidate[], string>(__TAURI_INVOKE("get_external_component_guidance_candidates", { view })),
	deferExternalComponentGuidanceForSession: (key: string) => typedError<null, string>(__TAURI_INVOKE("defer_external_component_guidance_for_session", { key })),
	/**
	 *  Components that HardwareVisualizer can set up on the user's request, in
	 *  display order.
	 */
	getExternalComponentSetupComponents: () => __TAURI_INVOKE<ExternalComponent[]>("get_external_component_setup_components"),
	getExternalComponentSetupStatus: (component: ExternalComponent) => typedError<ExternalComponentSetupStatus, string>(__TAURI_INVOKE("get_external_component_setup_status", { component })),
	// Run External Component Setup in an elevated child process and wait for it.
	runExternalComponentSetup: (component: ExternalComponent) => typedError<ExternalComponentSetupResult, string>(__TAURI_INVOKE("run_external_component_setup", { component })),
	// ## Get an aggregated CPU/RAM archive series
	getDataArchiveSeries: (hardwareType: DataArchiveHardwareType, dataStats: ArchiveDataStats, start: string, end: string, bucketWidthMs: number, bucketTimestamp: ArchiveBucketTimestamp) => typedError<ArchiveSeriesPoint[], string>(__TAURI_INVOKE("get_data_archive_series", { hardwareType, dataStats, start, end, bucketWidthMs, bucketTimestamp })),
	// ## Get an aggregated GPU archive series
	getGpuArchiveSeries: (dataType: GpuArchiveDataType, dataStats: ArchiveDataStats, gpuName: string, start: string, end: string, bucketWidthMs: number, bucketTimestamp: ArchiveBucketTimestamp) => typedError<ArchiveSeriesPoint[], string>(__TAURI_INVOKE("get_gpu_archive_series", { dataType, dataStats, gpuName, start, end, bucketWidthMs, bucketTimestamp })),
	// ## Get every archived fan's bucketed RPM series
	getFanArchiveSeries: (start: string, end: string, bucketWidthMs: number, bucketTimestamp: ArchiveBucketTimestamp) => typedError<FanArchiveSeries[], string>(__TAURI_INVOKE("get_fan_archive_series", { start, end, bucketWidthMs, bucketTimestamp })),
	// ## Get the bucketed ambient temperature and paired thermal delta series
	getAmbientArchiveSeries: (start: string, end: string, bucketWidthMs: number, bucketTimestamp: ArchiveBucketTimestamp) => typedError<AmbientArchiveSeries, string>(__TAURI_INVOKE("get_ambient_archive_series", { start, end, bucketWidthMs, bucketTimestamp })),
	// ## Get archived process stats for a period ending at `end_at`
	getProcessStats: (period: number, endAt: string) => typedError<ProcessStatRecord[], string>(__TAURI_INVOKE("get_process_stats", { period, endAt })),
	// ## Get archived process stats between two timestamps
	getProcessStatsInPeriod: (start: string, end: string) => typedError<ProcessStatRecord[], string>(__TAURI_INVOKE("get_process_stats_in_period", { start, end })),
	// ## Get GPU names that have archive records
	getGpuArchiveNames: () => typedError<string[], string>(__TAURI_INVOKE("get_gpu_archive_names")),
	// ## Get the long-range cooling trend (90-day / 1-year)
	getCoolingTrend: (days: number) => typedError<CoolingDailyTrendPoint[], string>(__TAURI_INVOKE("get_cooling_trend", { days })),
	// ## Get the long-range per-fan speed trend (90-day / 1-year)
	getCoolingFanTrend: (days: number) => typedError<CoolingFanTrend, string>(__TAURI_INVOKE("get_cooling_fan_trend", { days })),
	// ## Get the per-load-band baseline-vs-recent cooling comparison
	getCoolingBandComparison: () => typedError<CoolingBandComparison, string>(__TAURI_INVOKE("get_cooling_band_comparison")),
	// ## Get the idle cooling baseline delta and its observation state
	getCoolingBaselineDelta: () => typedError<CoolingBaselineDelta, string>(__TAURI_INVOKE("get_cooling_baseline_delta")),
	/**
	 *  ## Get the CPU load vs. CPU temperature Explorer for two windows
	 * 
	 *  `recent_days` is the requested length of the trailing window; Core
	 *  clamps it to the range the hourly rollup can answer for.
	 */
	getCoolingLoadTemperatureExplorer: (recentDays: number) => typedError<CoolingLoadTemperatureExplorer, string>(__TAURI_INVOKE("get_cooling_load_temperature_explorer", { recentDays })),
	// Get the co-variate comparison of the Thermal Delta windows for `band` - which archived factors moved with the Thermal Delta and which stayed within range, with each window's ΔT-per-watt fit (#2068). `band` is the CPU-load band the observation strip compares under; the windows, the comparability gate, and every judgement are Core's.
	getCoolingCovariateComparison: (band: CoolingLoadBand) => typedError<CoolingCovariateComparison, string>(__TAURI_INVOKE("get_cooling_covariate_comparison", { band })),
	getSettings: () => typedError<ClientSettings_Serialize, string>(__TAURI_INVOKE("get_settings")),
	setLanguage: (newLanguage: string) => typedError<null, string>(__TAURI_INVOKE("set_language", { newLanguage })),
	setTheme: (newTheme: Theme) => typedError<null, string>(__TAURI_INVOKE("set_theme", { newTheme })),
	setNavigationLayout: (newLayout: NavigationLayout) => typedError<null, string>(__TAURI_INVOKE("set_navigation_layout", { newLayout })),
	acknowledgeNavigationRestructureAnnouncement: () => typedError<null, string>(__TAURI_INVOKE("acknowledge_navigation_restructure_announcement")),
	setDisplayTargets: (newTargets: HardwareType[]) => typedError<null, string>(__TAURI_INVOKE("set_display_targets", { newTargets })),
	setPowerDisplayTargets: (newTargets: PowerDisplayTarget[]) => typedError<null, string>(__TAURI_INVOKE("set_power_display_targets", { newTargets })),
	setGraphSize: (newSize: GraphSize) => typedError<null, string>(__TAURI_INVOKE("set_graph_size", { newSize })),
	setGraphFitToWindow: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_graph_fit_to_window", { newValue })),
	setGraphMarginPx: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_graph_margin_px", { newValue })),
	setLineGraphType: (newType: LineGraphType) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_type", { newType })),
	setLineGraphBorder: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_border", { newValue })),
	setLineGraphFill: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_fill", { newValue })),
	setLineGraphColor: (target: HardwareType, newColor: string) => typedError<string, string>(__TAURI_INVOKE("set_line_graph_color", { target, newColor })),
	setLineGraphMix: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_mix", { newValue })),
	setLineGraphShowLegend: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_legend", { newValue })),
	setLineGraphShowScale: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_scale", { newValue })),
	setLineGraphShowTooltip: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_line_graph_show_tooltip", { newValue })),
	setBackgroundImgOpacity: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_background_img_opacity", { newValue })),
	setSelectedBackgroundImg: (fileId: string | null) => typedError<null, string>(__TAURI_INVOKE("set_selected_background_img", { fileId })),
	setTransparentUi: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_transparent_ui", { newValue })),
	setWindowOpacity: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_window_opacity", { newValue })),
	setGlassBlur: (newValue: number) => typedError<null, string>(__TAURI_INVOKE("set_glass_blur", { newValue })),
	setTemperatureUnit: (newUnit: TemperatureUnit) => typedError<null, string>(__TAURI_INVOKE("set_temperature_unit", { newUnit })),
	setHardwareArchiveEnabled: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_enabled", { newValue })),
	/**
	 *  Turn the SwitchBot Meter ambient source on or off (#2044). Takes
	 *  effect on the next launch, like the archive toggle beside it: the
	 *  ambient registry is built once at startup and read-only afterwards,
	 *  so the scan starts and stops with the process rather than
	 *  mid-session. The settings screen says so.
	 */
	setSwitchbotMeterEnabled: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_switchbot_meter_enabled", { newValue })),
	// Choose which SwitchBot device the ambient source reads, or clear the choice with `None`. The id is the device's Bluetooth address as twelve hex digits, as listed by `get_ambient_sensor_candidates`; it is stored lowercase, and anything else is refused. The running source switches to the new device at once, so no restart is needed.
	setSwitchbotMeterDevice: (deviceId: string | null) => typedError<null, string>(__TAURI_INVOKE("set_switchbot_meter_device", { deviceId })),
	// Every SwitchBot device heard within the last few minutes, in a stable device-id order, each with its reading in the preferred temperature unit; a device that has gone quiet drops out rather than showing an old reading as current. Returns an empty list on a machine where the ambient source is off, where no adapter exists, or where nothing has advertised yet - all of which look the same from here and are equally honest as "nothing to choose from".
	getAmbientSensorCandidates: () => typedError<AmbientSensorCandidate[], string>(__TAURI_INVOKE("get_ambient_sensor_candidates")),
	setHardwareArchiveRetentionDays: (newRetentionDays: number) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_retention_days", { newRetentionDays })),
	setHardwareArchiveScheduledDataDeletion: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_hardware_archive_scheduled_data_deletion", { newValue })),
	setStorageHealthRetentionDays: (newRetentionDays: number) => typedError<null, string>(__TAURI_INVOKE("set_storage_health_retention_days", { newRetentionDays })),
	setBurnInShift: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift", { newValue })),
	setBurnInShiftMode: (newValue: BurnInShiftMode) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_mode", { newValue })),
	setBurnInShiftPreset: (newValue: BurnInShiftPreset) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_preset", { newValue })),
	setBurnInShiftIdleOnly: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_idle_only", { newValue })),
	setBurnInShiftOptions: (newValue: {
	// Override interval (ms) for jump
	intervalMs?: number | null,
	// Override amplitude (px) for jump [x, y]
	amplitudePx?: [number, number] | null,
	// Idle threshold in ms
	idleThresholdMs?: number | null,
	// Drift cycle duration (sec)
	driftDurationSec?: number | null,
} | null) => typedError<null, string>(__TAURI_INVOKE("set_burn_in_shift_options", { newValue })),
	setTextSelectable: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_text_selectable", { newValue })),
	setTrayWidgetSettings: (newValue: TrayWidgetSettings_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set_tray_widget_settings", { newValue })),
	setCloseToTrayPreference: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_close_to_tray_preference", { newValue })),
	acknowledgeExternalComponentGuidanceKey: (key: string) => typedError<null, string>(__TAURI_INVOKE("acknowledge_external_component_guidance_key", { key })),
	setElevatedStartupMode: (newValue: boolean) => typedError<null, string>(__TAURI_INVOKE("set_elevated_startup_mode", { newValue })),
	readLicenseFile: () => typedError<string, string>(__TAURI_INVOKE("read_license_file")),
	readThirdPartyNoticesFile: () => typedError<string, string>(__TAURI_INVOKE("read_third_party_notices_file")),
	openLicenseFilePath: () => typedError<null, string>(__TAURI_INVOKE("open_license_file_path")),
	/**
	 *  Get background image
	 * 
	 *  - `file_id`: Image file ID
	 */
	getBackgroundImage: (fileId: string) => typedError<string, string>(__TAURI_INVOKE("get_background_image", { fileId })),
	// Get list of background images in BG_IMG_DIR_NAME directory
	getBackgroundImages: () => typedError<BackgroundImage[], string>(__TAURI_INVOKE("get_background_images")),
	/**
	 *  Save background image
	 * 
	 *  - `image_data`: Base64 string of image data
	 *  - returns: `file_id`
	 * 
	 *  ### TODO
	 *  - Use JsImage https://docs.rs/tauri/2.1.1/tauri/image/enum.JsImage.html
	 *    - Implemented with Base64 for now as type definition with specta was difficult
	 * 
	 */
	saveBackgroundImage: (imageData: string) => typedError<string, string>(__TAURI_INVOKE("save_background_image", { imageData })),
	/**
	 *  Delete background image
	 *  - `file_id`: Image file ID
	 */
	deleteBackgroundImage: (fileId: string) => typedError<null, string>(__TAURI_INVOKE("delete_background_image", { fileId })),
	// Set window decoration state
	setDecoration: (isDecorated: boolean) => typedError<null, string>(__TAURI_INVOKE("set_decoration", { isDecorated })),
	// Restart the application
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	// Returns whether the current process is running with administrator privileges.
	isProcessElevated: () => typedError<boolean, string>(__TAURI_INVOKE("is_process_elevated")),
	/**
	 *  Stop monitoring and exit the process.
	 * 
	 *  Phase 5 (#1408): the explicit Quit path. Keep it gated to the
	 *  internal callers that the lifecycle module owns — Phase 6's tray
	 *  menu and the future "Quit" UX from #1275. Until those land, this
	 *  command is reachable only from devtools / tauri-specta-generated
	 *  bindings, which is enough to validate the cleanup ordering.
	 */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	// Returns whether close-to-tray can safely be enabled in this session.
	isCloseToTrayAvailable: () => typedError<boolean, string>(__TAURI_INVOKE("is_close_to_tray_available")),
	// Mark the frontend close-to-tray dialog listener as ready.
	markCloseToTrayListenerReady: () => typedError<null, string>(__TAURI_INVOKE("mark_close_to_tray_listener_ready")),
	// Hide the main window through the App-owned close-to-tray lifecycle.
	hideMainWindowToTray: () => typedError<null, string>(__TAURI_INVOKE("hide_main_window_to_tray")),
};

/** Events */
export const events = {
	hardwareMonitorUpdate: makeEvent<HardwareMonitorUpdate>("hardware-monitor-update"),
};

/* Types */
/**
 *  One bucket of the Cooling Insight ambient lane (#2046). `ambientAvg`
 *  null means no minute in the bucket carried an ambient row, and
 *  `deltaAvg` null means none carried both an ambient row and a CPU
 *  package temperature - neither is a measured zero, and the lane must
 *  break there rather than interpolate.
 */
export type AmbientArchiveBucket = {
	timestamp: number,
	ambientAvg: number | null,
	deltaAvg: number | null,
};

/**
 *  The ambient lane of one Cooling Insight timeline range (#2046).
 *  `AMBIENT_ARCHIVE` is row-per-source, so `sources` names the labels that
 *  actually contributed to this window; an empty list is exactly how a
 *  machine with no environmental sensor reports itself.
 */
export type AmbientArchiveSeries = {
	sources: string[],
	buckets: AmbientArchiveBucket[],
};

// One SwitchBot device the radio is hearing, offered for selection. It carries the reading rather than a model name because model identity cannot be trusted from these broadcasts, and because the temperature is what actually tells the user which device sits near the intake.
export type AmbientSensorCandidate = {
	// Full address, the value to pass back when selecting this device.
	deviceId: string,
	/**
	 *  Last four hex digits - enough to tell devices apart, and the tail
	 *  owners tend to name them by.
	 */
	shortId: string,
	// The latest reading, already in `temperature_unit`.
	temperature: number,
	/**
	 *  The unit `temperature` is expressed in - the user's preference,
	 *  applied at the App boundary like every other temperature shown.
	 */
	temperatureUnit: TemperatureUnit,
	humidityPercent: number | null,
	// Whether this is the device currently selected.
	selected: boolean,
};

export type ArchiveBucketTimestamp = "start" | "end";

export type ArchiveDataStats = "avg" | "max" | "min";

export type ArchiveSeriesPoint = {
	timestamp: number,
	value: number | null,
};

/**
 *  Wire error enum exposed to the frontend through tauri-specta.
 * 
 *  Core reports platform failures as
 *  `hardviz_core::enums::error::PlatformError`; the App services and
 *  commands translate them into these frontend-stable variants.
 */
export type BackendError = "cpuInfoNotAvailable" | "storageInfoNotAvailable" | "memoryInfoNotAvailable" | "graphicInfoNotAvailable" | "networkInfoNotAvailable" | "networkUsageNotAvailable" | "unexpectedError";

/**
 *  - `file_id` : Image file ID
 *  - `image_data` : Base64 string of image data
 */
export type BackgroundImage = {
	fileId: string,
	imageData: string,
};

export type BurnInShiftMode = "jump" | "drift";

export type BurnInShiftOptions = {
	// Override interval (ms) for jump
	intervalMs?: number | null,
	// Override amplitude (px) for jump [x, y]
	amplitudePx?: [number, number] | null,
	// Idle threshold in ms
	idleThresholdMs?: number | null,
	// Drift cycle duration (sec)
	driftDurationSec?: number | null,
};

export type BurnInShiftPreset = "gentle" | "balanced" | "aggressive";

export type ClientSettings = ClientSettings_Serialize | ClientSettings_Deserialize;

export type ClientSettings_Deserialize = {
	version: string,
	language: string,
	theme: Theme,
	navigationLayout: NavigationLayout,
	uiAnnouncementVersion: number,
	/**
	 *  Current announcement schema version. This is wire metadata, not a
	 *  persisted user preference.
	 */
	currentUiAnnouncementVersion: number,
	displayTargets: HardwareType[],
	powerDisplayTargets: PowerDisplayTarget[],
	graphSize: GraphSize,
	graphFitToWindow: boolean,
	graphMarginPx: number,
	lineGraphType: LineGraphType,
	lineGraphBorder: boolean,
	lineGraphFill: boolean,
	lineGraphColor: LineGraphColorStringSettings,
	lineGraphMix: boolean,
	lineGraphShowLegend: boolean,
	lineGraphShowScale: boolean,
	lineGraphShowTooltip: boolean,
	backgroundImgOpacity: number,
	selectedBackgroundImg: string | null,
	transparentUi: boolean,
	windowOpacity: number,
	glassBlur: number,
	temperatureUnit: TemperatureUnit,
	hardwareArchive: HardwareArchiveSettings,
	storageHealth: StorageHealthSettings,
	environmentalSensors: EnvironmentalSensorSettings,
	burnInShift: boolean,
	burnInShiftMode: BurnInShiftMode,
	burnInShiftPreset: BurnInShiftPreset,
	burnInShiftIdleOnly: boolean,
	burnInShiftOptions: BurnInShiftOptions | null,
	textSelectable: boolean,
	closeToTray: boolean,
	closeToTrayChoiceMade: boolean,
	externalComponentGuidance: ExternalComponentGuidanceSettings,
	elevatedStartupMode: boolean,
	trayWidget: TrayWidgetSettings_Deserialize,
};

export type ClientSettings_Serialize = {
	version: string,
	language: string,
	theme: Theme,
	navigationLayout: NavigationLayout,
	uiAnnouncementVersion: number,
	/**
	 *  Current announcement schema version. This is wire metadata, not a
	 *  persisted user preference.
	 */
	currentUiAnnouncementVersion: number,
	displayTargets: HardwareType[],
	powerDisplayTargets: PowerDisplayTarget[],
	graphSize: GraphSize,
	graphFitToWindow: boolean,
	graphMarginPx: number,
	lineGraphType: LineGraphType,
	lineGraphBorder: boolean,
	lineGraphFill: boolean,
	lineGraphColor: LineGraphColorStringSettings,
	lineGraphMix: boolean,
	lineGraphShowLegend: boolean,
	lineGraphShowScale: boolean,
	lineGraphShowTooltip: boolean,
	backgroundImgOpacity: number,
	selectedBackgroundImg: string | null,
	transparentUi: boolean,
	windowOpacity: number,
	glassBlur: number,
	temperatureUnit: TemperatureUnit,
	hardwareArchive: HardwareArchiveSettings,
	storageHealth: StorageHealthSettings,
	environmentalSensors: EnvironmentalSensorSettings,
	burnInShift: boolean,
	burnInShiftMode: BurnInShiftMode,
	burnInShiftPreset: BurnInShiftPreset,
	burnInShiftIdleOnly: boolean,
	burnInShiftOptions: BurnInShiftOptions | null,
	textSelectable: boolean,
	closeToTray: boolean,
	closeToTrayChoiceMade: boolean,
	externalComponentGuidance: ExternalComponentGuidanceSettings,
	elevatedStartupMode: boolean,
	trayWidget: TrayWidgetSettings_Serialize,
};

/**
 *  One band's ambient-adjusted baseline-vs-recent comparison (#2045): the
 *  same two windows as the absolute comparison, but over the thermal
 *  delta, so a rise the weather explains can be told apart from a rise
 *  the cooling explains. `comparable` follows the same
 *  both-sides-or-nothing rule as the absolute reading.
 */
export type CoolingAmbientAdjustedBandComparison = {
	baseline: CoolingBandDeltaWindowSummary,
	recent: CoolingBandDeltaWindowSummary,
	comparable: boolean,
};

/**
 *  The ambient-normalized reading of the same idle drift (#2045): how far
 *  the machine's idle rise *above ambient* has moved, rather than how far
 *  its absolute idle temperature has moved. A flat delta under a rising
 *  absolute temperature says the room warmed up; a rising delta says the
 *  machine did. `delta` is null unless `comparable`.
 */
export type CoolingAmbientAdjustedBaselineDelta = {
	/**
	 *  The ΔT baseline's own lifecycle and window, which advance
	 *  independently of the absolute baseline beside it.
	 */
	baseline: CoolingDeltaBaselineState,
	recent: CoolingBandDeltaWindowSummary,
	delta: number | null,
	comparable: boolean,
};

/**
 *  Cooling Insight's load-band comparison, gated by the same baseline
 *  lifecycle as [`CoolingBaselineState`]: no comparison exists yet while
 *  the baseline is still establishing.
 */
export type CoolingBandComparison = { status: "establishing"; qualifyingDays: number; requiredDays: number } | { status: "established"; baselineWindowStartDate: string; baselineWindowEndDate: string; recentWindowStartDate: string; recentWindowEndDate: string; bands: CoolingBandComparisonEntry[]; ambientAdjustedBaseline: CoolingDeltaBaselineState };

// One CPU-load band's baseline-vs-recent comparison.
export type CoolingBandComparisonEntry = {
	band: CoolingLoadBand,
	baseline: CoolingBandWindowSummary,
	recent: CoolingBandWindowSummary,
	comparable: boolean,
	/**
	 *  The ambient-adjusted reading of the same two windows (#2045). Null
	 *  when neither window recorded a paired minute for this band, which is
	 *  the normal state on a machine with no environmental sensor; a
	 *  present value with `comparable: false` instead means ambient data
	 *  exists but one window is still too thin to compare.
	 */
	ambientAdjusted: CoolingAmbientAdjustedBandComparison | null,
};

/**
 *  One band's weighted-average thermal delta (CPU package temperature
 *  minus ambient) and its paired-sample coverage over a date window
 *  (#2045). Named `deltaAvg` rather than `temperatureAvg` because it is a
 *  difference, not an absolute temperature; `sampleMinutes` counts only
 *  minutes where both readings existed, so it is always at most the
 *  matching [`CoolingBandWindowSummary`]'s.
 */
export type CoolingBandDeltaWindowSummary = {
	deltaAvg: number | null,
	sampleMinutes: number,
};

/**
 *  One band's temperature median within one Explorer window, with the
 *  evidence behind it.
 */
export type CoolingBandMedian = {
	temperatureMedian: number | null,
	pointCount: number,
	sampleMinutes: number,
};

/**
 *  One band's two window medians and the delta between them. `delta` is
 *  absent whenever `comparable` is `false`.
 */
export type CoolingBandMedianDelta = {
	band: CoolingLoadBand,
	baseline: CoolingBandMedian,
	recent: CoolingBandMedian,
	delta: number | null,
	comparable: boolean,
};

// One CPU-load band's temperature summary for a single day.
export type CoolingBandTemperature = {
	avg: number | null,
	max: number | null,
	min: number | null,
	sampleMinutes: number,
};

/**
 *  One band's weighted-average temperature and sample coverage over a
 *  date window (either the baseline window or the recent window).
 */
export type CoolingBandWindowSummary = {
	temperatureAvg: number | null,
	sampleMinutes: number,
};

/**
 *  Cooling Insight's baseline delta card: the current drift, its
 *  classification, and the daily series that classification was derived
 *  from.
 */
export type CoolingBaselineDelta = {
	baseline: CoolingBaselineState,
	recent: CoolingRecentIdleSummary,
	delta: number | null,
	observation: CoolingDeltaObservation,
	dailyDeltas: CoolingDailyDelta[],
	sustainedDays: number,
	/**
	 *  The ambient-normalized reading of the same drift (#2045). Always
	 *  present, carrying its own lifecycle: a machine with no environmental
	 *  sensor reports an establishing ΔT baseline at zero qualifying days
	 *  rather than a fabricated number. Every field above is computed
	 *  exactly as it was before #2045 whatever this one says.
	 */
	ambientAdjusted: CoolingAmbientAdjustedBaselineDelta,
};

/**
 *  Lifecycle of the idle cooling baseline (see
 *  `hardviz_core::persistence::cooling_baseline::BaselineState`).
 */
export type CoolingBaselineState = { status: "establishing"; qualifyingDays: number; requiredDays: number } | { status: "established"; idleTemperatureAvg: number; windowStartDate: string; windowEndDate: string; sampleMinutes: number };

/**
 *  Why the two windows are, or are not, compared (#2068):
 *  `tooFewPairedMinutes` when one window carries fewer Thermal Delta
 *  paired minutes in the compared band than Core requires (including a
 *  recent window no source paired at all), `differentAmbientSource` when
 *  the recent window's dominant source is not the one the Thermal Delta
 *  Baseline was established from (#2062).
 */
export type CoolingCovariateComparability = "comparable" | "tooFewPairedMinutes" | "differentAmbientSource";

/**
 *  Cooling Insight's co-variate comparison for one CPU-load band
 *  (#2068), gated by the Thermal Delta Baseline's lifecycle exactly as
 *  the ambient-adjusted band comparison is: while it establishes there is
 *  no baseline window to read. Temperatures cross the wire as Core holds
 *  them, exactly like the other Cooling Insight readings: the ambient
 *  medians in Celsius, and the ΔT change at matched power and every
 *  fit's slope and intercept in kelvin - the frontend applies the
 *  preferred temperature unit, scaling a difference without the offset.
 *  Package power is in watts and fan speed in rpm, which no unit
 *  preference touches.
 */
export type CoolingCovariateComparison = { status: "establishing"; qualifyingDays: number; requiredDays: number } | { status: "established"; band: CoolingLoadBand; baselineSource: string; baselineWindowStartDate: string; baselineWindowEndDate: string; recentSource: string | null; recentWindowStartDate: string; recentWindowEndDate: string; baselinePairedMinutes: number; recentPairedMinutes: number; packagePower: CoolingFactorComparison; ambientTemperature: CoolingFactorComparison; loadBandShare: CoolingFactorComparison; fans: CoolingFanCovariateComparison[]; baselineFit: CoolingLeastSquaresFit | null; recentFit: CoolingLeastSquaresFit | null; deltaAtBaselineMedianPower: number | null; comparable: boolean; comparability: CoolingCovariateComparability };

/**
 *  One trailing-7-day-window delta against the baseline, ending on
 *  `date`.
 */
export type CoolingDailyDelta = {
	date: string,
	delta: number,
};

/**
 *  One day's `cooling_daily_summary` row, for the 90-day/1-year Cooling
 *  Insight trend. A date the rollup has no row for is simply absent from
 *  the response array - never a zero-filled entry.
 */
export type CoolingDailyTrendPoint = {
	date: string,
	coverageMinutes: number,
	idle: CoolingBandTemperature,
	low: CoolingBandTemperature,
	mid: CoolingBandTemperature,
	high: CoolingBandTemperature,
	/**
	 *  The day's CPU package power, independent of the bands above. Absent
	 *  on a machine with no CPU power source, which is what makes the
	 *  timeline's power lane capability-dependent.
	 */
	power: CoolingPowerSummary,
};

/**
 *  Lifecycle of the ambient-normalized (ΔT) cooling baseline (#2045),
 *  mirroring [`CoolingBaselineState`]. It establishes over its own window
 *  of days that carry paired hardware/ambient minutes, which on a machine
 *  whose environmental sensor arrived late is a different - often much
 *  later - range than the absolute baseline's.
 */
export type CoolingDeltaBaselineState = { status: "establishing"; qualifyingDays: number; requiredDays: number } | { status: "established"; deltaTemperatureAvg: number; windowStartDate: string; windowEndDate: string; sampleMinutes: number };

/**
 *  Cooling Insight's read of the current idle-temperature drift. The
 *  frontend renders this enum as-is; the +5/+10 degC thresholds and the
 *  3-day sustain requirement stay behind Core's boundary (#1666).
 */
export type CoolingDeltaObservation = "establishing" | "notComparable" | "withinRange" | "sustainedMildRise" | "sustainedLargeRise";

/**
 *  One of the Explorer's two windows: its calendar range and its scatter
 *  points. Per-band medians live on [`CoolingBandMedianDelta`], which
 *  pairs both windows' values for a band.
 */
export type CoolingExplorerWindow = {
	startDate: string,
	endDate: string,
	points: CoolingLoadTemperaturePoint[],
};

/**
 *  One archived co-variate across the two windows (#2068): each window's
 *  median of its daily medians, `change` as `recent - baseline` (present
 *  only when both are), and the judgement Core made. A window that never
 *  archived the factor reads null there, not 0 - which is what keeps an
 *  `absent` factor from looking like a machine drawing no power.
 */
export type CoolingFactorComparison = {
	baseline: number | null,
	recent: number | null,
	change: number | null,
	judgement: CoolingFactorJudgement,
};

/**
 *  Where one co-variate's recent median sits against the baseline
 *  window's own daily spread (#2068), decided in Core: `withinRange` and
 *  `moved` are read against the baseline window's interquartile range of
 *  daily medians; `notComparable` is a factor both windows carry that
 *  cannot be judged (too few baseline days for a range, no recent day,
 *  or the windows as a whole not comparable); `absent` is a factor
 *  neither window ever archived - never reported as zero, and never as
 *  having stayed within range.
 */
export type CoolingFactorJudgement = "withinRange" | "moved" | "notComparable" | "absent";

/**
 *  One fan's speed across the two windows, with each window's
 *  ΔT-per-rpm fit (#2068). `fanSource` is the fan's stable
 *  channel-derived identifier, as archived.
 */
export type CoolingFanCovariateComparison = {
	fanSource: string,
	speed: CoolingFactorComparison,
	baselineFit: CoolingLeastSquaresFit | null,
	recentFit: CoolingLeastSquaresFit | null,
};

/**
 *  One `(date, fan)` row of the fan rollup, carried with its own date so a
 *  day the fan recorded nothing is simply absent from the series rather
 *  than present as 0 RPM. Not `Option`-shaped: every row that exists
 *  carries a real measurement, and an Inactive Fan Reading is a real 0.
 */
export type CoolingFanDay = {
	date: string,
	rpmAvg: number,
	rpmMax: number,
	rpmMin: number,
	sampleMinutes: number,
};

/**
 *  The long-range fan trend plus the evidence the caller needs to read an
 *  empty `series` correctly (#2022). An empty series means either that the
 *  machine has no readable fan or that the rollup has not summarized one
 *  yet - it only summarizes completed days - and only
 *  `archiveHasReadings` tells those apart, because the one-minute fan
 *  archive holds a reading the moment collection starts.
 */
export type CoolingFanTrend = {
	series: CoolingFanTrendSeries[],
	archiveHasReadings: boolean,
};

/**
 *  One fan's daily series for the 90-day / 1-year fan lane (#2022). One
 *  series per fan rather than one row per day, because how many fans a
 *  machine exposes is configuration-dependent; an empty response is how a
 *  machine with no readable fan reports itself.
 */
export type CoolingFanTrendSeries = {
	// The fan's stable channel-derived identifier, as archived.
	source: string,
	days: CoolingFanDay[],
};

/**
 *  The least-squares line through one window's paired minutes (#2068).
 *  For the ΔT-power fit `slope` is kelvin per watt and `intercept` the
 *  ΔT the line reads at zero power; for the ΔT-fan fit the slope is
 *  kelvin per rpm. The whole fit is null, rather than a flat line, where
 *  the window had fewer than two paired minutes or no spread in one
 *  reading.
 */
export type CoolingLeastSquaresFit = {
	slope: number,
	intercept: number,
	pearsonR: number,
	pairedMinutes: number,
};

/**
 *  A CPU-load band as the frontend names one, both in results and as
 *  the band a query is asked for (`get_cooling_covariate_comparison`).
 */
export type CoolingLoadBand = "idle" | "low" | "mid" | "high";

/**
 *  Cooling Insight's load-vs-temperature Explorer, gated by the same
 *  baseline lifecycle as [`CoolingBandComparison`].
 */
export type CoolingLoadTemperatureExplorer = { status: "establishing"; qualifyingDays: number; requiredDays: number } | { status: "established"; baseline: CoolingExplorerWindow; recent: CoolingExplorerWindow; bandDeltas: CoolingBandMedianDelta[] };

/**
 *  One hour's (load, temperature) pair, as scattered by the Explorer.
 * 
 *  `hourStart` is the local wall-clock hour string the hourly rollup
 *  stores (`"%Y-%m-%d %H:00"`), for the same reason dates cross as
 *  `"%Y-%m-%d"`: it is already the key Core compares and sorts on.
 */
export type CoolingLoadTemperaturePoint = {
	hourStart: string,
	cpuUsageAvg: number,
	cpuTemperatureAvg: number,
	sampleMinutes: number,
};

/**
 *  One day's CPU package power draw in watts (#2021). Not a
 *  [`CoolingBandTemperature`] despite the identical shape: power is
 *  summarized over the whole day rather than per CPU-load band, and it is
 *  a different unit. `sampleMinutes == 0` means no archived minute that
 *  day carried a power reading, and `avg`/`max`/`min` are then all null -
 *  the machine has no CPU power source, not 0 W.
 */
export type CoolingPowerSummary = {
	avg: number | null,
	max: number | null,
	min: number | null,
	sampleMinutes: number,
};

/**
 *  The trailing recent-window idle summary the baseline is compared
 *  against.
 */
export type CoolingRecentIdleSummary = {
	windowStartDate: string,
	windowEndDate: string,
	idleTemperatureAvg: number | null,
	sampleMinutes: number,
};

export type CpuInfo = {
	name: string,
	vendor: string,
	coreCount: number,
	clock: number,
	clockUnit: string,
	cpuName: string,
};

export type DataArchiveHardwareType = "cpu" | "cpuTemperature" | "cpuPower" | "gpuPower" | "anePower" | "packagePower" | "memory";

export type DiskKind = "hdd" | "ssd" | "other";

export type DownloadEvent = { event: "started"; data: {
	contentLength: string | null,
} } | { event: "progress"; data: {
	chunkLength: string,
} } | { event: "finished" };

/**
 *  Wire-format mirror of
 *  [`hardviz_core::settings::EnvironmentalSensorSettings`] (#2044). The
 *  canonical definition lives in `hardviz_core::settings` so the ambient
 *  provider registration doesn't need to know about Tauri or specta.
 *  This App-side struct exists only because the frontend wire format
 *  requires `specta::Type`.
 */
export type EnvironmentalSensorSettings = {
	switchbotMeterEnabled?: boolean,
	/**
	 *  Which device the ambient source reads, or `None` until one is
	 *  chosen. Unlike the rest of this struct it reaches the frontend
	 *  because choosing is the interaction: several sensors in one room
	 *  can read degrees apart, so the screen must be able to say which one
	 *  is selected and offer the others.
	 */
	switchbotMeterDevice?: string | null,
};

export type ExternalComponent = "pawnio" | "smartctl";

export type ExternalComponentGuidanceCandidate = {
	key: string,
	component: ExternalComponent,
	usage: ExternalComponentUsage,
	reasonKind: ExternalComponentReasonKind,
	missingSignals: string[],
	affectedDeviceCount: number | null,
	diagnosticDetail: string | null,
};

export type ExternalComponentGuidanceSettings = {
	acknowledgedKeys?: string[],
};

export type ExternalComponentGuidanceView = "dashboard" | "cpuDetail" | "storageHealth";

export type ExternalComponentModuleFileState = {
	fileName: string,
	present: boolean,
};

export type ExternalComponentReasonKind = "missing" | "permission" | "misconfigured" | "failed";

export type ExternalComponentRuntimeInstallState = "notInstalled" | "installed" | "unknown";

export type ExternalComponentRuntimeState = {
	state: ExternalComponentRuntimeInstallState,
	version: string | null,
	installLocation: string | null,
	// Why the state is unknown, when it is.
	detail: string | null,
};

export type ExternalComponentSetupFailureStage = "stateUnknown" | "stagingDirectory" | "downloadRuntime" | "verifyRuntime" | "startInstaller" | "installerExit" | "downloadModules" | "verifyModules" | "archiveContents" | "placeModules" | "incomplete" | "unsupportedPlatform" | "panicked" | "other";

export type ExternalComponentSetupOutcome = "alreadyInstalled" | "installed" | "rebootRequired" | "cancelled" | "failed";

export type ExternalComponentSetupResult = {
	component: ExternalComponent,
	outcome: ExternalComponentSetupOutcome,
	// Present for `failed` outcomes.
	failureStage: ExternalComponentSetupFailureStage | null,
	/**
	 *  Free-text detail known to the app process (never taken from the
	 *  elevated child, which reports through its exit code only).
	 */
	detail: string | null,
	// The state after the run, so the UI does not need a second call.
	status: ExternalComponentSetupStatus,
};

export type ExternalComponentSetupStatus = {
	component: ExternalComponent,
	support: ExternalComponentSetupSupport,
	runtime: ExternalComponentRuntimeState,
	moduleFiles: ExternalComponentModuleFileState[],
	pinnedRuntimeVersion: string,
	pinnedModulesVersion: string,
	// True when nothing is left for setup to do.
	complete: boolean,
	/**
	 *  Why setup cannot run right now (unsupported platform or an uncertain
	 *  state), or `None` when it can.
	 */
	setupBlocker: string | null,
};

export type ExternalComponentSetupSupport = "supported" | "unsupportedPlatform";

export type ExternalComponentUsage = "cpuPackageTemperature" | "motherboardSensors" | "storageHealth";

/**
 *  One archived fan's bucketed RPM series (#2022). Row-per-fan on disk, so
 *  how many series come back depends on the machine's configuration rather
 *  than on a fixed set the caller names; an empty response is exactly how a
 *  machine with no readable fan reports itself.
 */
export type FanArchiveSeries = {
	// The fan's stable channel-derived identifier, as archived.
	source: string,
	points: ArchiveSeriesPoint[],
};

export type FanSpeedStatus = "active" | "inactive" | "invalid";

export type GpuArchiveDataType = "usage" | "temp" | "dedicatedMemory";

export type GpuMemoryUsage = {
	inUseBytes: string | null,
	allocBytes: string | null,
};

export type GpuMonitorData = {
	gpuId: string,
	gpuName: string,
	gpuUsage: number | null,
	gpuTemperature: number | null,
	gpuSource: string,
	gpuDedicatedMemoryUsageKb: number | null,
	gpuCoolerLevel: number | null,
};

export type GpuUsageResult = {
	usage: number,
	source: string,
};

export type GraphSize = "sm" | "md" | "lg" | "xl" | "2xl";

export type GraphicInfo = {
	id: string,
	name: string,
	vendorName: string,
	clock: number,
	memorySize: string,
	memorySizeDedicated: string,
	coreCount: string | null,
};

/**
 *  Wire-format mirror of [`hardviz_core::settings::HardwareArchiveSettings`].
 * 
 *  The canonical definition lives in `hardviz_core::settings` so the
 *  archive worker (and any future Core consumer) doesn't need to know
 *  about Tauri or specta. This App-side struct exists only because the
 *  frontend wire format requires `specta::Type`.
 */
export type HardwareArchiveSettings = {
	enabled?: boolean,
	scheduledDataDeletion?: boolean,
	retentionDays?: number,
};

export type HardwareMonitorUpdate = {
	cpuUsage: number,
	memoryUsage: number,
	gpus: GpuMonitorData[],
	processorsUsage: number[],
	cpuPowerWatts: number | null,
	gpuPowerWatts: number | null,
	anePowerWatts: number | null,
	packagePowerWatts: number | null,
	cpuPowerSupport: SensorSupport,
	// Headline CPU temperature in the user's preferred unit. Currently Windows only.
	cpuTemperature: number | null,
	// All named temperature sensors (thermal zones) in the user's preferred unit.
	sensorTemperatures: NameValue[],
	// Motherboard temperature sensors in the user's preferred unit.
	motherboardTemperatures: MotherboardTemperatureValue[],
	// Motherboard fan speeds in RPM.
	motherboardFanSpeeds: MotherboardFanSpeedValue[],
	motherboardFanSupport: SensorSupport,
};

export type HardwareType = "cpu" | "memory" | "gpu";

// Structure of settings to send to client
export type LineGraphColorStringSettings = {
	cpu: string,
	memory: string,
	gpu: string,
};

export type LineGraphType = "default" | "step" | "linear" | "basis";

export type LiveStorageHealth = {
	deviceId: string,
	displayName: string,
	temperatureCelsius: number | null,
	availableSparePercent: number | null,
	percentageUsed: number | null,
	mediaErrors: number | null,
	unsafeShutdownCount: number | null,
	powerOnHours: number | null,
	powerCycleCount: number | null,
	collectedAt: string,
};

export type MemoryInfo = {
	size: string,
	clock: number,
	clockUnit: string,
	memoryCount: number,
	totalSlots: number,
	memoryType: string,
	isDetailed: boolean,
};

export type MotherboardFanSpeedValue = {
	name: string,
	rpm: number | null,
	status: FanSpeedStatus,
	source: string,
};

export type MotherboardInfo = {
	manufacturer: string,
	product: string,
	version: string,
	serialNumber: string,
	biosVendor: string,
	biosVersion: string,
	biosReleaseDate: string,
};

export type MotherboardTemperatureValue = {
	name: string,
	value: number,
	source: string,
};

export type NameValue = {
	name: string,
	value: number,
};

export type NavigationLayout = "grouped" | "classic";

export type NetworkInfo = {
	description: string | null,
	macAddress: string | null,
	ipv4: string[],
	ipv6: string[],
	linkLocalIpv6: string[],
	ipSubnet: string[],
	defaultIpv4Gateway: string[],
	defaultIpv6Gateway: string[],
};

export type PawnIoRuntimeDiagnostics = {
	installLocation: string | null,
	dllPath: string | null,
	modulePath: string | null,
	pawnioAvailable: boolean,
	libraryLoadable: boolean,
	driverOpenable: boolean,
	moduleLoadable: boolean,
	version: number | null,
	fallbackReason: string | null,
};

export type PowerDisplayTarget = "cpu" | "gpu" | "ane" | "package";

export type ProcessInfo = ProcessInfo_Serialize | ProcessInfo_Deserialize;

export type ProcessInfo_Deserialize = {
	pid: number,
	name: string,
	cpuUsage: string,
	memoryUsage: string,
};

export type ProcessInfo_Serialize = {
	pid: number,
	name: string,
	cpuUsage: string,
	memoryUsage: string,
};

export type ProcessStatRecord = {
	pid: number,
	process_name: string,
	avg_cpu_usage: number,
	avg_memory_usage: number,
	total_execution_sec: number,
	latest_timestamp: string,
};

export type SensorSupport = "unknown" | "supported" | "unsupported";

export type SizeUnit = "B" | "KB" | "MB" | "GB";

export type StorageHealthRecord = {
	deviceId: string,
	displayName: string,
	model: string | null,
	protocol: string | null,
	capacityBytes: number | null,
	date: string,
	healthStatus: StorageHealthStatus,
	warningLevel: StorageWarningLevel,
	temperatureCelsius: number | null,
	powerOnHours: number | null,
	percentageUsed: number | null,
	availableSparePercent: number | null,
	reallocatedSectorCount: number | null,
	currentPendingSectorCount: number | null,
	offlineUncorrectableCount: number | null,
	mediaErrors: number | null,
	errorLogEntries: number | null,
	unsafeShutdownCount: number | null,
	warningReasons: string[],
	collectedAt: string,
};

/**
 *  Wire-format mirror of [`hardviz_core::settings::StorageHealthSettings`]. The
 *  canonical definition lives in `hardviz_core::settings` so the
 *  storage health record worker doesn't need to know about Tauri or specta.
 */
export type StorageHealthSettings = {
	enabled?: boolean,
	retentionDays?: number,
};

export type StorageHealthStatus = "good" | "warning" | "critical" | "unknown";

export type StorageInfo = {
	name: string,
	size: number,
	sizeUnit: SizeUnit,
	free: number,
	freeUnit: SizeUnit,
	storageType: DiskKind,
	fileSystem: string,
};

export type StorageWarningLevel = "none" | "warning" | "critical" | "unknown";

export type SuperIoChipIdAttempt = {
	vendor: SuperIoVendor,
	idHigh: number | null,
	idLow: number | null,
	chipId: number | null,
	absent: boolean,
	error: string | null,
	exitError: string | null,
};

export type SuperIoChipIdDiagnostics = {
	platformSupported: boolean,
	pawnio: PawnIoRuntimeDiagnostics | null,
	slots: SuperIoChipIdSlotProbe[],
	error: string | null,
};

export type SuperIoChipIdSlotProbe = {
	slot: number,
	indexPort: number,
	dataPort: number,
	attempts: SuperIoChipIdAttempt[],
	error: string | null,
};

export type SuperIoVendor = "nuvoton" | "ite";

export type SysInfo = {
	cpu: CpuInfo | null,
	memory: MemoryInfo | null,
	gpus: GraphicInfo[] | null,
	storage: StorageInfo[],
	motherboard: MotherboardInfo | null,
};

export type TemperatureUnit = "C" | "F";

export type Theme = "system" | "light" | "dark" | "darkPlus" | "sky" | "grove" | "sunset" | "nebula" | "orbit" | "cappuccino" | "espresso";

export type TrayMetric = "cpu" | "gpu" | "gpu-temp";

export type TrayWidgetSettings = TrayWidgetSettings_Serialize | TrayWidgetSettings_Deserialize;

export type TrayWidgetSettings_Deserialize = {
	enabled?: boolean,
	metricOrder?: TrayMetric[],
	visibleMetrics?: TrayMetric[],
	updateIntervalSecs?: number,
	metrics?: TrayMetric[],
};

export type TrayWidgetSettings_Serialize = {
	enabled: boolean,
	metricOrder: TrayMetric[],
	visibleMetrics: TrayMetric[],
	updateIntervalSecs: number,
};

export type UpdateMetadata = {
	version: string,
	currentVersion: string,
	notes: string | null,
	pubDate: string | null,
};

export type UpdaterError = "NoPendingUpdate" | { Updater: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    void _assertTypedErrorFollowsContract;
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        return { status: "error", error: e as E };
    }
}
// @ts-expect-error tauri-specta's generated contract assertion leaves E unused under noUnusedLocals.


const _assertTypedErrorFollowsContract: <T, E>(result: Promise<T>) => Promise<any> = typedError;

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

